[pre-commit]
parallel = true

[pre-commit.commands.ruff]
root = "nixsa-build"
glob = "*.py"
run = ".venv/bin/ruff check --fix --exit-non-zero-on-fix {all_files}"

[pre-commit.commands.ruff-fmt]
root = "nixsa-build"
glob = "*.py"
# Needed since currenty ruff-fmt doesn't support both fixing and returning non-zero on change.
# See https://github.com/astral-sh/ruff/issues/8191
run = "if ! .venv/bin/ruff format --check {all_files}; then .venv/bin/ruff format {all_files}; false; fi"

[pre-commit.commands.pylint]
root = "nixsa-build"
glob = "*.py"
run = ".venv/bin/pylint -rn -sn {all_files}"

[pre-commit.commands.mypy]
root = "nixsa-build"
glob = "*.py"
run = ".venv/bin/mypy --strict {all_files}"
