name: Release Tags

concurrency:
  group: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # In order to upload artifacts to GitHub releases

jobs:
  build-x86_64-linux:
    uses: ./.github/workflows/build-x86_64-linux.yml
    with:
      cache-key: release-x86_64-linux-artifacts-${{ github.sha }}
  # build-aarch64-linux:
  #   uses: ./.github/workflows/build-aarch64-linux.yml
  #   with:
  #     cache-key: release-aarch64-linux-artifacts-${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build-x86_64-linux
      # - build-aarch64-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create artifacts directory
        run: mkdir -p ./artifacts

      - name: Fetch cached x86_64-linux binary
        uses: actions/cache/restore@v3
        with:
          path: nixsa.tar.xz
          key: release-x86_64-linux-artifacts-${{ github.sha }}
      - name: Move artifact to artifacts directory
        run: mv ./nixsa.tar.xz ./artifacts/nixsa-x86_64-linux.tar.xz

      # - name: Fetch cached aarch64-linux binary
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: nixsa.tar.xz
      #     key: release-aarch64-linux-artifacts-${{ github.sha }}
      # - name: Move artifact to artifacts directory
      #   run: mv ./nixsa.tar.xz ./artifacts/nixsa-aarch64-linux.tar.xz

      - name: Publish Release to GitHub (Tag)
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          draft: true
          files: |
            artifacts/**
